"""innitial migration

Revision ID: 401968771534
Revises: 
Create Date: 2022-03-06 20:14:52.093449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '401968771534'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_hash')
    # ### end Alembic commands ###
